### PR TITLE
Percent padding support. Solves #186

### PR DESCRIPTION
**Pull request by albertocs-noma**
Padding by percent added in the same fashion as margins. Solves #186

### CODE REVIEW

**Comment by albertocsouto** [comment]
Hi, we're using this feature in apps with millions of users, any chance of being reviewed? Thanks!

**Comment by lucdion** [comment]
Sorry @albertocsouto, I have missed that PR

**Review by lucdion — CHANGES_REQUESTED** [review]
Thanks for this addition.

Please update the README, and also add a simple unit test for each methods in `PaddingSpec`

**Comment by lucdion** [comment]
Also, please update your work branch with the latest `master` branch.

**Comment by albertocs-noma** [comment]
> Sorry @albertocsouto, I have missed that PR

Applied suggested changes, thanks for your patience :)

**Review by lucdion — APPROVED** [review]
Excellent 👌

**Comment by lucdion** [comment]
Last thing @albertocs-noma , could you update your branch with recent changes from the main branch? To fix that:

image

**Comment by albertocs-noma** [comment]
> Last thing @albertocs-noma , could you update your branch with recent changes from the main branch? To fix that:
> 
> image

Should be solved, sorry for the inconvenience!

**Comment by lucdion** [comment]
Release created https://github.com/layoutBox/FlexLayout/releases/tag/1.3.23

**Pull request merged**
