### PR TITLE
Update yoga core to v2.0

### PR DESCRIPTION
**Pull request by OhKanghoon**
## Background

- YogaKit has been removed from yoga official repository.
  - https://github.com/facebook/yoga/commit/7097b12b921bb7bcfb738175baeee02db7a2b06a
- Update the yoga core to the most recent version of yoga 2.0, and manage YogaKit in FlexLayout from now on.
- FlexLayout can later add 'gap' features added in yoga 2.0

### CODE REVIEW

**Review by lucdion — COMMENTED** [review]
Thanks @OhKanghoon for this major update.
Please fix CI issues https://github.com/layoutBox/FlexLayout/actions/runs/6283516421/job/17064055867?pr=230 🙏

**Comment by OhKanghoon** [comment]
Hi @lucdion 

I usually work with spm so I missed the header setting of xcodeproj 😅
I fix ci in 6cc5128 commit, so you can check the commit

Facebook's YogaKit didn't fix it, but FlexLayout's YogaKit also reflected all the changes
- 990d45b
- 538cdb2
- 6c09d6d

**Comment by OhKanghoon** [comment]
Hi @lucdion,

Could you please review my Pull Request when you have a moment? 
It's been pending for a while, and your input would be really helpful.

Thanks!

**Comment by lucdion** [comment]
Sorry @OhKanghoon , I wanted to take the time to check that is doesn't break anything important. 
It looks good. I will switch FlexLayout version to 2.0 to match Yoga version

**Review by lucdion — APPROVED** [review]
Thanks for this important change @OhKanghoon 👏

**Comment by lucdion** [comment]
FlexLayout 2.0.02 is available https://github.com/layoutBox/FlexLayout/releases/tag/2.0.02

Thanks again

**Pull request merged**
