### PR TITLE
Change the access control of margin padding functions

### PR DESCRIPTION
**Pull request by OhKanghoon**
- Change the access control of function that using NSDirectionalEdgeInsets

### CODE REVIEW

**Comment by OhKanghoon** [comment]
Hello @lucdion 👋🏻
I found the access control issue and fixed it
If there's no problem, please release next version 🙏🏻

**Review by lucdion — APPROVED** [review]
Thanks 👍

**Comment by lucdion** [comment]
Release 1.3.24 available https://github.com/layoutBox/FlexLayout/releases/tag/1.3.24

**Comment by OhKanghoon** [comment]
Thanks @lucdion !

The wrong tag [1.10.1](https://github.com/layoutBox/FlexLayout/releases/tag/1.10.1) has been uploaded, so it would be good to remove it.

**Comment by lucdion** [comment]
Oups, done

**Pull request merged**
