### PR TITLE
Enhance Swift Package experience

### PR DESCRIPTION
**Pull request by OhKanghoon**
## Background

- Change the Swift Package Manager to be available without `FLEXLAYOUT_SWIFT_PACKAGE` flag

## Contents

- add public header path
- remove `FLEXLAYOUT_SWIFT_PACKAGE`
- remove library for internal (FlexLayoutYoga, FlexLayoutYogaKit)
- move the unit test to the swift package with XCTest

### CODE REVIEW

**Review by luoxiu — APPROVED** [review]

**Review by lucdion — APPROVED** [review]
Sorry @OhKanghoon for the long delay, I missed the PR.
Really nice clean up, really good job 👏 

Last thing, could you update the README here https://github.com/layoutBox/FlexLayout#in-an-xcode-target

Thanks

**Comment by OhKanghoon** [comment]
> Sorry @OhKanghoon for the long delay, I missed the PR. Really nice clean up, really good job 👏
> 
> Last thing, could you update the README here https://github.com/layoutBox/FlexLayout#in-an-xcode-target
> 
> Thanks

Thank you for your review.
I remove `FLEXLAYOUT_SWIFT_PACKAGE` related content of README.md 8c5177d9cbceeccce8c2859cbd4d562d4c68523a

**Comment by lucdion** [comment]
@OhKanghoon , you must update the PR's branch. Thanks

**Comment by OhKanghoon** [comment]
> @OhKanghoon , you must update the PR's branch. Thanks

Checked it! 👍

**Comment by lucdion** [comment]
I have merged an published a new release. Thanks

**Pull request merged**
