### PR TITLE
Fix error that occur when creating XCFramework

### PR DESCRIPTION
**Pull request by OhKanghoon**
## Background

- Public header issue occurs when using Objective-C package in [Tuist](https://github.com/tuist/tuist)'s Dependency. To resolve this issue, I want to provide xcframework.
- Resolve the issue that occurs when creating xcframework due to duplicate 'postfix operator %'.

## Contents

- remove unnecessary files and headers
  - Modified to manage yoga directly in FlexLayout. Buck dependency is now unnecessary.
- remove duplicated postfix operator
- update Podfile.lock
- remove Info.plist
- move `FlexLayout.h` to public header directory

### CODE REVIEW

**Comment by OhKanghoon** [comment]
Hi @lucdion
I resolve issues that arise when creating xcframework, and clean up the project's unnecessary setup.
Please review this PR. 😄

**Review by lucdion — APPROVED** [review]
Nice cleanup. Thanks 👍

**Comment by OhKanghoon** [comment]
> Nice cleanup. Thanks 👍

@lucdion 
Thanks for review.
I need to fix the xcframework issue, so can I ask you for a new version release?

**Comment by lucdion** [comment]
Sorry, I forgot to do it. 2.0.06 is now available. Thanks

**Pull request merged**
