### PR TITLE
Adds Swift Package Manager Support

### LINKED ISSUE #144: SPM support
Hello,

any plans to support Swift Package Manager soon?

### PR DESCRIPTION
**Pull request by gcox**
Resolves #144 

* Isolates all the C & Non-C code
* Adds a swift package manifest with targets for FlexLayout, FlexLayoutYoga, and FlexLayoutYogaKit
* Moves the public headers to the [target]/include/[target] folder per [Apple's documentation](https://github.com/apple/swift-package-manager/blob/master/Documentation/Usage.md#creating-c-language-targets)
* Adds a new target to the `FlexLayoutSample` project called `FlexLayoutExampleSPM` that imports FlexLayout via the Swift package.

`NS_ENUM typedefs` don't seem to be translated to Swift enums when imported via a module. Because of that, static values were added to the various NS_ENUM types as extensions when in the context of a Swift package. Perhaps there's a build setting to eliminate the need for that?

## CAVEAT
To build a target that imports FlexLayout via the new swift package, you'll need to add `FLEXLAYOUT_SWIFT_PACKAGE=1` to the target's `GCC_PREPROCESSOR_DEFINITIONS` build setting. The new `FlexLayoutExampleSPM` target does this, so look there for an example.

The reason is that there appears to be an Xcode/SwiftPM/Both bug regarding the `SWIFT_PACKAGE` macro. As a result, when building an application target that includes FlexLayout via the new Swift package, the `SWIFT_PACKAGE` macro is undefined when compiling the `FlexLayoutYogaKit` target, which causes the build to fail. To work around this, I defined a new macro in the swift package called `FLEXLAYOUT_SWIFT_PACKAGE` and replaced all usages of `SWIFT_PACKAGE` with `FLEXLAYOUT_SWIFT_PACKAGE`. This way, you can safely define the macro in your own targets and allow the build to succeed.

### CODE REVIEW

**Comment by pju-trifork** [comment]
Consider updating Installation section in README.md

**Comment by pju-trifork** [comment]
For some reason FlexLayout is failing to build when I install it on app target using SPM. I am able to build the package alone.

It seems that `SWIFT_PACKAGE` macro is either undefined or ignored when `FlexLayoutYogaKit` is being built.

I have tried to fix it ([link to branch](https://github.com/pju-trifork/FlexLayout/tree/spm-10-pju)) by explicitly defining `SWIFT_PACKAGE` in `Package.swift`, unfortunately without any luck.

```
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "/Users/povilasjuzeliunas/Library/Developer/Xcode/DerivedData/AppName-chgnrgvfpwnbhsfhdndefkgdwdpc/SourcePackages/checkouts/FlexLayout/Sources/YogaKit/include/YogaKit/YGLayout+Private.h"
        ^
/Users/povilasjuzeliunas/Library/Developer/Xcode/DerivedData/AppName-chgnrgvfpwnbhsfhdndefkgdwdpc/SourcePackages/checkouts/FlexLayout/Sources/YogaKit/include/YogaKit/YGLayout+Private.h:8:9: note: in file included from /Users/povilasjuzeliunas/Library/Developer/Xcode/DerivedData/AppName-chgnrgvfpwnbhsfhdndefkgdwdpc/SourcePackages/checkouts/FlexLayout/Sources/YogaKit/include/YogaKit/YGLayout+Private.h:8:
#import "YGLayout.h"
        ^
/Users/povilasjuzeliunas/Library/Developer/Xcode/DerivedData/AppName-chgnrgvfpwnbhsfhdndefkgdwdpc/SourcePackages/checkouts/FlexLayout/Sources/YogaKit/include/YogaKit/YGLayout.h:15:9: error: 'YGEnums.h' file not found
#import "YGEnums.h"
        ^
<unknown>:0: error: could not build Objective-C module 'FlexLayoutYogaKit'

```

Screenshot 2020-02-27 at 10 50 14

**Comment by gcox** [comment]
@pju-trifork Yeah, what a pain. I think this is a bug in Xcode or SwiftPM or both. See my latest commit which makes a simple workaround possible, and probably safe.

**Comment by gcox** [comment]
@pju-trifork Added a new target to the `FlexLayoutSample` project, `FlexLayoutExampleSPM`, that imports `FlexLayout` as a swift package so playing with this is trivial now.

**Comment by gcox** [comment]
@lucdion I added it. Since SPM requires some type of qualification of a specific version/tag/branch/etc, we may need to tweak the README again if there's another version bump before this gets merged.

**Comment by conversun** [comment]
why not merge ?

**Pull request merged**
