### PR TITLE
Add baseline item support!

### PR DESCRIPTION
**Pull request by rantingmong**
Add `baseline` `alignItem` support for `UILabel`, `UITextField`, and `UITextView`.

For now baseline support is only for the first baseline. Last baseline needs a change into Yoga itself.

Modifications are mostly in YogaKit's YGLayout.

### CODE REVIEW

**Comment by lucdion** [comment]
Any idea why Travis-CI didn't report the status @rantingmong?

**Comment by rantingmong** [comment]
That I am not aware of, maybe because I'm pull requesting from a fork I made? Or the branch is not master?

**Comment by rantingmong** [comment]
I checked the build status [here](https://travis-ci.org/github/layoutBox/FlexLayout/builds/691569586), it completed successfully! I did some light research and found about [this](https://github.com/travis-ci/travis-ci/issues/10204), it might be something to do with how GitHub's configuration on how to receive the message from Travis.

**Comment by lucdion** [comment]
One last thing that I missed @rantingmong , it would be great if you could update this section of the documentation https://github.com/layoutBox/FlexLayout#alignitems. Don't bother with the image if you want.

Thanks!

**Comment by rantingmong** [comment]
Sure!

**Pull request merged**
